POST http://localhost:3005/api/monitores HTTP/1.1
Content-Type: application/json

{
		"codigoascii": 5559,
		"codigosasa": "79",
		"detalle": "Test create post monitores",
		"nube": false,
		"ultimosync": "2021-06-30T17:30:31.098Z",
		"tareas": [
			{
				"nombre": "SERVICIO_SYNC_RECLAMOS",
				"activa": true,
				"descripcion": "Matiene sincronizado los reclamos que ingresan en consorciosenred con ada4d",
				"intervalo": 10,
				"ultimaEjecucion": "2021-06-10T00:30:31.098Z"
			}
		]
}

###
POST http://localhost:3005/api/monitores HTTP/1.1
Content-Type: application/json

{
		"codigoascii": 5559
}